spring:
  data:
    mongodb:
      username: rootuser
      password: rootpass
      host: localhost
      port: 27017
      database: notification
      authentication-database: admin
    #  kafka producer config
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.peters.ecommerce.notification.kafka.order.OrderConfirmation,paymentConfirmation:com.peters.ecommerce.notification.kafka.payment.PaymentConfirmation
  mail:
    host: localhost
    port: 1025
    username: depitaztech
    password: depitaztech
    properties:
      mail:
        smtp:
          trust: "*"
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000
server:
  port: 8040